import { createContext, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  rw: {
    "Your orders": "Ibyo watumije",
    "Explore": "Ibyo wakora",
    "Sort products": "Tondeka ibicuruzwa",
    "Fruit": "Imbuto",
    "Food": "Ibiribwa",
    "Devices": "Ibikoresho by'ikoranabuhanga",
    "Home": "Mu rugo",
    "Care": "Isuku n'ubwiza",
    "pending": "Birategereje",
    "processing": "Birimo gutunganywa",
    "shipped": "Byoherejwe",
    "delivered": "Byageze aho bijya",
    "cancelled": "Byahagaritswe",
    "Shop": "Gura",
    "Profile": "Umwirondoro",
    "Admin": "Ubuyobozi",
    "Sign in": "Injira",
    "Sign out": "Sohoka",
    "Choose language": "Hitamo ururimi",
    "English": "Icyongereza",
    "Kinyarwanda": "Ikinyarwanda",
    "Your bag": "Agaseke kawe",
    "Open cart, {count} items": "Fungura agaseke, ibintu {count}",
    "A BRIGHTER KIND OF EVERYDAY": "Ubuzima bwa buri munsi burusheho kuba bwiza",
    "The everyday,": "Ibyo dukenera buri munsi,",
    "well chosen.": "byatoranyijwe neza.",
    "Fruit for the week, pantry staples, and useful things for home and on the go. Good finds, all in one place.": "Imbuto z'icyumweru, ibiribwa by'ibanze n'ibikoresho by'ingirakamaro byo mu rugo no mu rugendo. Byose ahantu hamwe.",
    "A little more lovely, every day.": "Buri munsi urusheho kuryoha.",
    "FRESH PICKS": "Ibishya byatoranyijwe",
    "From the market to your everyday": "Biva ku isoko bikakugeraho",
    "Shop by category": "Gura ukurikije icyiciro",
    "A GOOD PLACE TO START": "Ahantu heza ho gutangirira",
    "Small joys, sorted.": "Ibyiza bito byatoranyijwe.",
    "All": "Byose",
    "THE EDIT": "Ibyatoranyijwe",
    "Find your new favorite": "Shaka icyo uzakunda",
    "Little things that make a day feel a little better.": "Ibintu bito bituma umunsi urushaho kuba mwiza.",
    "Search products": "Shakisha ibicuruzwa",
    "Filter products by category": "Shungura ibicuruzwa ukurikije icyiciro",
    "Saved": "Ibyabitswe",
    "Sort:": "Tondeka:",
    "Featured": "Ibyatoranyijwe",
    "Price: low to high": "Igiciro: gito kijya ku kinini",
    "Price: high to low": "Igiciro: kinini kijya ku gito",
    "Name": "Izina",
    "Finding the good stuff...": "Turimo gushaka ibyiza...",
    "Try again": "Ongera ugerageze",
    "Your saved finds": "Ibyo wabitswe",
    "A few good things": "Bimwe mu byiza",
    "find": "igicuruzwa",
    "finds": "ibicuruzwa",
    "No saved finds yet. Tap a heart to keep something close.": "Nta bicuruzwa wabika. Kanda ku mutima ubike icyo ukunda.",
    "Browse everything": "Reba ibicuruzwa byose",
    "No products found. Try another search.": "Nta bicuruzwa bibonetse. Gerageza gushakisha ukundi.",
    "Chosen with care": "Byatoranyijwe ubwitonzi",
    "Everyday favourites, thoughtfully gathered.": "Ibyo ukunda buri munsi byatoranyijwe neza.",
    "Room for discovery": "Hari byinshi byo kuvumbura",
    "Fresh produce, home finds and useful tech.": "Imbuto nshya, ibyo mu rugo n'ikoranabuhanga by'ingirakamaro.",
    "Keep what you love": "Bika ibyo ukunda",
    "Save your favourite finds for next time.": "Bika ibyo ukunda uzabigarukireho.",
    "Sold out": "Byashize",
    "Add to bag": "Shyira mu gaseke",
    "Add to bag +": "Shyira mu gaseke +",
    "Everyday": "Ibyo buri munsi",
    "A thoughtful pick for your everyday.": "Igicuruzwa cyiza wahisemo cya buri munsi.",
    "Remove {name} from favorites": "Kuramo {name} mu byo ukunda",
    "Add {name} to favorites": "Shyira {name} mu byo ukunda",
    "Close cart": "Funga agaseke",
    "Sign in to see and save items in your bag.": "Injira urebe kandi ubike ibiri mu gaseke.",
    "Your bag is waiting for something good.": "Agaseke kawe karategereje ibyiza.",
    "Unavailable product": "Igicuruzwa kitabonetse",
    "Decrease quantity": "Gabanya umubare",
    "Increase quantity": "Ongera umubare",
    "Subtotal": "Igiteranyo",
    "Delivery details are collected at checkout.": "Aderesi yo kukugezaho izuzuzwa urangiza gutumiza.",
    "Delivery address": "Aderesi yo kukugezaho",
    "Street, city, postal code": "Umuhanda, umujyi, kode y'iposita",
    "Pay with": "Ishyura ukoresheje",
    "Pay from your mobile money account": "Ishyura ukoresheje amafaranga yo kuri telefoni",
    "Not available yet": "Ntibiraboneka",
    "After placing your order, follow the secure USSD prompt on your phone. Payment is confirmed by the store; never enter your PIN on this website.": "Nyuma yo gutumiza, kurikiza amabwiriza ya USSD kuri telefoni yawe. Ububiko ni bwo bwemeza ubwishyu; ntukandike PIN kuri uru rubuga.",
    "Placing order...": "Turimo kohereza ubusabe...",
    "Place order · {total}": "Ohereza ubusabe · {total}",
    "Create your account": "Fungura konti",
    "Close": "Funga",
    "Your name": "Amazina yawe",
    "Email address": "Imeyili",
    "Password": "Ijambo ry'ibanga",
    "Please wait...": "Tegereza gato...",
    "Create account": "Fungura konti",
    "Already have an account?": "Usanzwe ufite konti?",
    "Create an account": "Fungura konti",
    "Complete your payment": "Rangiza ubwishyu",
    "Pay {total} with {provider}.": "Ishyura {total} ukoresheje {provider}.",
    "Merchant number": "Nomero y'umucuruzi",
    "Amount": "Amafaranga",
    "Open {provider} USSD on this phone": "Fungura USSD ya {provider} kuri iyi telefoni",
    "Open this order on your mobile phone to launch USSD. Code:": "Fungura iri tumiza kuri telefoni yawe ukoreshe USSD. Kode:",
    "Enter your payment PIN only in the phone’s secure USSD prompt. Never share it with the store or enter it on this website.": "Andika PIN yo kwishyura muri USSD yizewe ya telefoni gusa. Ntuyisangize ububiko cyangwa ngo uyandike kuri uru rubuga.",
    "Done": "Byarangiye",
    "YOUR GREEN MARKET": "Green Market yawe",
    "Sign in to view your orders.": "Injira urebe ibyo watumije.",
    "Loading your orders...": "Turimo gupakira ibyo watumije...",
    "Preparing PDF...": "Turimo gutegura PDF...",
    "Paid": "Yishyuwe",
    "Order notifications": "Ubutumwa ku byo watumije",
    "Get a device notification when your order is received, its status changes, or payment is confirmed—even when this site is closed.": "Menyeshwa igihe ibyo watumije byakiriwe, imiterere yabyo ihindutse cyangwa ubwishyu bwemejwe, n'igihe uru rubuga rudafunguye.",
    "Notifications aren’t supported in this browser.": "Iyi browser ntishyigikira ubutumwa.",
    "Checking...": "Turimo kugenzura...",
    "Turn off notifications": "Zimya ubutumwa",
    "Enable order notifications": "Fungura ubutumwa ku byo watumije",
    "Enabled for this browser and account.": "Byafunguwe kuri iyi browser na konti.",
    "Messages and replies": "Ubutumwa n'ibisubizo",
    "messages": "ubutumwa",
    "Loading your messages...": "Turimo gupakira ubutumwa bwawe...",
    "Green Market team replied": "Ikipe ya Green Market yagusubije",
    "Waiting for a reply": "Hategerejwe igisubizo",
    "Download receipt": "Kuramo inyemezabuguzi",
    "Your profile": "Umwirondoro wawe",
    "Sign in to your account": "Injira muri konti yawe",
    "Your profile, order history, and support messages are available after you sign in.": "Umwirondoro, amateka y'ibyo watumije n'ubutumwa bwo kugufasha biboneka umaze kwinjira.",
    "ACCOUNT DETAILS": "AMAKURU YA KONTI",
    "Store administrator": "Umuyobozi w'ububiko",
    "Green Market customer": "Umukiriya wa Green Market",
    "Account shortcuts": "Iby'ingenzi kuri konti",
    "Track fulfilment and payment confirmation": "Kurikirana itangwa n'ubwishyu",
    "Contact support": "Vugana n'ubufasha",
    "Send a message, wish, or issue report": "Ohereza ubutumwa, icyifuzo cyangwa raporo y'ikibazo",
    "Support replies": "Ibisubizo by'ubufasha",
    "Read responses from the Green Market team": "Soma ibisubizo by'ikipe ya Green Market",
    "WE’RE HERE TO HELP": "TURI HANO KUGUFASHA",
    "Send us a message": "Twandikire",
    "Your name and email are taken from your signed-in account so our team can identify and reply to you.": "Amazina na imeyili bikurwa muri konti yawe kugira ngo ikipe itamenye kandi igusubize.",
    "What can we help with?": "Twagufasha iki?",
    "General message": "Ubutumwa rusange",
    "Product wish or suggestion": "Icyifuzo cyangwa igitekerezo ku bicuruzwa",
    "Report an issue": "Menyesha ikibazo",
    "Help request": "Saba ubufasha",
    "Your message": "Ubutumwa bwawe",
    "Tell us how we can help, what you’d like to see, or what needs attention...": "Tubwire uko twagufasha, icyo wifuza cyangwa ikibazo ubonye...",
    "Sending...": "Turimo kohereza...",
    "Send to Green Market": "Ohereza kuri Green Market",
    "No products yet. Add your first one above.": "Nta bicuruzwa biraboneka. Banza wongere igicuruzwa hejuru.",
    "Find a product to update or remove": "Shakisha igicuruzwa cyo guhindura cyangwa gukuraho",
    "Search by product name, category, or slug": "Shakisha ukoresheje izina, icyiciro cyangwa slug",
    "Customer messages": "Ubutumwa bw'abakiriya",
    "awaiting reply": "butegereje igisubizo",
    "total": "bose hamwe",
    "Customer messages and reports will appear here.": "Ubutumwa na raporo by'abakiriya bizagaragara hano.",
    "Write a reply": "Andika igisubizo",
    "Update reply": "Hindura igisubizo",
    "Write a helpful response. It will appear in the customer’s profile inbox.": "Andika igisubizo gifasha. Kizagaragara mu butumwa bw'umukiriya.",
    "Send reply": "Ohereza igisubizo",
    "Save reply": "Bika igisubizo",
    "Find a product": "Shaka igicuruzwa",
    "BUSINESS OVERVIEW": "INCAMAKE Y'UBUCURUZI",
    "Order reports": "Raporo z'ibitumizwa",
    "From": "Kuva",
    "To": "Kugeza",
    "Order status": "Imiterere y'itumiza",
    "All statuses": "Imiterere yose",
    "Creating PDF...": "Turimo gukora PDF...",
    "Export report PDF": "Kuramo raporo ya PDF",
    "Matching orders": "Ibitumizwa bihuye",
    "Order value": "Agaciro k'ibitumizwa",
    "Confirmed paid": "Amafaranga yemejwe",
    "No orders have been placed yet.": "Nta byo umuntu aratumiza.",
    "STORE MANAGEMENT": "IMICUNGIRE Y'UBUBIKO",
    "Admin dashboard": "Imbonerahamwe y'ubuyobozi",
    "Manage your products and keep every order moving.": "Cunga ibicuruzwa kandi ukurikiranire hafi ibitumizwa.",
    "Enable notifications": "Fungura ubutumwa",
    "Notifications on": "Ubutumwa burafunguye",
    "Notifications unavailable": "Ubutumwa ntibuboneka",
    "Refresh": "Ongera urebe",
    "Loading store management...": "Turimo gupakira imicungire y'ububiko...",
    "CATALOG": "IBICURUZWA",
    "Add a product": "Ongeraho igicuruzwa",
    "Update product": "Hindura igicuruzwa",
    "products": "ibicuruzwa",
    "Product name": "Izina ry'igicuruzwa",
    "Category": "Icyiciro",
    "Price": "Igiciro",
    "Stock": "Umubare uhari",
    "Description": "Ibisobanuro",
    "Product image URL": "Aderesi y'ifoto y'igicuruzwa",
    "Image description": "Ibisobanuro by'ifoto",
    "Slug (optional)": "Slug (si ngombwa)",
    "Saving...": "Turimo kubika...",
    "Save changes": "Bika impinduka",
    "Add product": "Ongeraho igicuruzwa",
    "Cancel edit": "Reka guhindura",
    "Edit": "Hindura",
    "Remove": "Kuraho",
    "All orders": "Ibitumizwa byose",
    "Status": "Imiterere",
    "Payment:": "Ubwishyu:",
    "Confirmation": "Kwemeza",
    "Awaiting confirmation": "Hategerejwe kwemezwa",
    "New around here?": "Ni ubwa mbere hano?",
    "STAY IN THE LOOP": "KOMEZA KUMENYA AMAKURU",
    "Help centre": "Ubufasha",
    "Shopping guide": "Uko ugura",
    "Shop everything": "Gura byose",
    "Your profile & support": "Umwirondoro n'ubufasha",
    "Visit & contact": "Aho turi n'uko watwandikira",
    "Information": "Amakuru",
    "Contact us": "Twandikire",
    "Contact the developer": "Vugana n'uwakoze uru rubuga",
    "Good fruit, useful things, and a few small upgrades for everyday life.": "Imbuto nziza, ibikoresho by'ingirakamaro n'ibindi byiza bya buri munsi.",
    "Thoughtfully picked. Ready for real life.": "Byatoranyijwe neza. Byiteguye ubuzima busanzwe.",
    "A good find can make an ordinary day.": "Ikintu cyiza gishobora kurimbisha umunsi usanzwe.",
    "HERE TO HELP": "TURI HANO KUGUFASHA",
    "A SIMPLE WAY TO SHOP": "UBURYO BWOROHEJE BWO KUGURA",
    "CLEAR AND FAIR": "AMABWIRIZA ASOBANUTSE",
    "YOUR INFORMATION": "AMAKURU YAWE",
    "Store policies": "Amabwiriza y'ububiko",
    "Privacy": "Ibanga",
    "Contact": "Twandikire",
    "Contact Green Market": "Vugana na Green Market",
    "×": "×",
    "Back to shopping": "Subira ku bicuruzwa",
    "Order {code}": "Icyatumijwe {code}",
    "Close payment instructions": "Funga amabwiriza yo kwishyura",
    "Your order was placed.": "Ibyo watumije byakiriwe.",
    "Payment is not confirmed automatically; the store will verify it.": "Ubwishyu ntibwemezwa ako kanya; ububiko buzabugenzura.",
    "Could not create the PDF receipt. Please try again.": "PDF y'inyemezabuguzi ntiyakozwe. Ongera ugerageze.",
    "Could not load your support messages.": "Ntibishobotse gupakira ubutumwa bwo kugufasha.",
    "Could not send your message.": "Ntibishobotse kohereza ubutumwa bwawe.",
    "Thanks for getting in touch. Your message is in your account inbox.": "Murakoze kutwandikira. Ubutumwa bwawe buri mu butumwa bwa konti yawe.",
    "YOUR INBOX": "UBUTUMWA BWAWE",
    "Your support conversations will appear here.": "Ubutumwa bwo kugufasha buzagaragara hano.",
    "No orders yet. Your next favorite is out there.": "Nta byo watumije. Icyo uzakunda kirahari.",
    "Could not load your orders.": "Ntibishobotse gupakira ibyo watumije.",
    "Order history": "Amateka y'ibyo watumije",
    "Payment not recorded": "Ubwishyu ntibwanditswe",
    "MTN MoMo": "MTN MoMo",
    "Airtel Money": "Airtel Money",
    "Bank of Kigali": "Bank of Kigali",
    "Fast mobile money payment": "Kwishyura vuba ukoresheje amafaranga yo kuri telefoni",
    "Pay with your Airtel wallet": "Ishyura ukoresheje konti ya Airtel Money",
    "Bank transfer · confirmed by the store": "Kohereza kuri banki · byemezwa n'ububiko",
    "BK account number used to pay": "Nomero ya konti ya BK uzakoresha wishyura",
    "Mobile money number": "Nomero ya telefoni yo kwishyura",
    "Enter your BK account number": "Andika nomero ya konti yawe ya BK",
    "We use this to help the store match your transfer. Transfer instructions will be confirmed with the store.": "Iyi nomero ifasha ububiko kugenzura ubwishyu bwawe. Ubusobanuro bwo kohereza buzemezwa n'ububiko.",
    "Enter the number you will use. Never enter your mobile money PIN here.": "Andika nomero uzakoresha. Ntukandike PIN ya telefoni hano.",
    "Payments are confirmed by the store. Never enter your PIN on this website.": "Ubwishyu bwemezwa n'ububiko. Ntukandike PIN yawe kuri uru rubuga.",
    "Enter a valid BK account number.": "Andika nomero nyayo ya konti ya BK.",
    "Enter a valid Rwanda mobile number.": "Andika nomero ya telefoni yo mu Rwanda nyayo.",
    "Your BK account": "Konti yawe ya BK",
    "Amount to transfer": "Amafaranga yo kohereza",
    "Contact the store for its Bank of Kigali transfer details. Your order remains awaiting confirmation until the store verifies payment.": "Vugana n'ububiko kugira ngo baguhe amakuru ya konti ya Bank of Kigali. Icyatumijwe ntikizemezwa kugeza ububiko bugenzuye ubwishyu.",
    "Payment account": "Konti yakoreshejwe mu kwishyura",
    "Separate checkout for": "Gutumiza muri ubu bubiko bikorwa ukwabyo:",
    "Remove “{name}” from your store?": "Ukureho “{name}” mu bubiko bwawe?",
    "Order updated.": "Icyatumijwe cyahinduwe.",
    "orders": "ibyo batumije",
    "Payment confirmed": "Ubwishyu bwemejwe",
    "Awaiting payment confirmation": "Hategerejwe kwemezwa k'ubwishyu",
    "Current status:": "Imiterere:",
    "Fulfilment": "Itangwa",
    "Orders": "Ibitumizwa",
    "Sign in and open Order history to review the latest fulfilment and payment status. Order updates are also available as browser notifications when you enable them in your profile.": "Injira ufungure amateka y'ibyo watumije urebe imiterere n'ubwishyu. Ushobora no gufungura ubutumwa bukumenyesha impinduka muri profayili yawe.",
    "Payments": "Ubwishyu",
    "Choose MTN MoMo, Airtel Money, or Bank of Kigali at checkout. Mobile-money orders include a secure USSD hand-off; for Bank of Kigali, contact the store for its transfer details. Payment is not automatic; the store confirms it after checking the payment. Never enter a payment PIN on this website.": "Iyo urangiza gutumiza, hitamo MTN MoMo, Airtel Money cyangwa Bank of Kigali. Ubwishyu bwo kuri telefoni bukurikiza amabwiriza ya USSD; kuri Bank of Kigali, vugana n'ububiko kugira ngo baguhe amakuru yo kohereza. Ububiko ni bwo bwemeza ubwishyu bumaze kubugenzura. Ntukandike PIN kuri uru rubuga.",
    "Need a hand?": "Ukeneye ubufasha?",
    "Send a support message, wish, or issue report from your profile. Our team’s reply will appear in your profile inbox.": "Ohereza ubutumwa, icyifuzo cyangwa raporo y'ikibazo muri profayili yawe. Igisubizo cy'ikipe kizagaragara mu butumwa bwawe.",
    "Find help with your account, orders, payments, or delivery.": "Shaka ubufasha kuri konti, ibyo watumije, ubwishyu cyangwa itangwa.",
    "A few quick steps from finding something useful to following your order.": "Intambwe nke zo guhitamo igicuruzwa no gukurikirana ibyo watumije.",
    "1. Find your favourites": "1. Shaka ibyo ukunda",
    "Browse the catalog, search for a product, and add available items to your bag.": "Reba ibicuruzwa, shakisha icyo ushaka, ugishyire mu gaseke.",
    "2. Check out securely": "2. Rangiza gutumiza mu mutekano",
    "Sign in, enter your delivery address, choose MTN MoMo, Airtel Money, or Bank of Kigali, and provide the payer's phone or account number. Your order total and item list are shown before placing the order.": "Injira, andika aderesi yo kukugezaho, uhitemo MTN MoMo, Airtel Money cyangwa Bank of Kigali, wandike nomero ya telefoni cyangwa konti izishyura. Reba igiteranyo n'urutonde rw'ibicuruzwa mbere yo gutumiza.",
    "3. Complete payment": "3. Rangiza ubwishyu",
    "Use the provider’s secure USSD prompt on your phone. Green Market never asks for your payment PIN.": "Koresha amabwiriza ya USSD yizewe ya telefoni. Green Market ntizigera igusaba PIN yo kwishyura.",
    "4. Follow your order": "4. Kurikirana ibyo watumije",
    "Open Order history to see status and payment confirmation. Enable notifications in your profile for updates when you are away from the site.": "Fungura amateka y'ibyo watumije urebe imiterere n'ubwishyu. Fungura ubutumwa muri profayili kugira ngo umenye amakuru utari ku rubuga.",
    "Important information about orders, fulfilment, payments, and support.": "Amakuru y'ingenzi yerekeye ibitumizwa, itangwa, ubwishyu n'ubufasha.",
    "Order fulfilment": "Itangwa ry'ibitumizwa",
    "Orders move through pending, processing, shipped, and delivered. An order may be cancelled when necessary; its reserved stock is then returned.": "Ibitumizwa bigira imiterere yo gutegereza, gutunganywa, koherezwa no kugera aho bijya. Icyatumijwe gishobora guhagarikwa igihe bibaye ngombwa; ibicuruzwa byari byagenewe icyo gitumizwa bisubizwa mu bubiko.",
    "Payment confirmation": "Kwemeza ubwishyu",
    "Mobile-money payment is completed with your provider; Bank of Kigali transfers are confirmed by the store. Orders remain awaiting confirmation until the store verifies payment and marks it paid.": "Ubwishyu bwo kuri telefoni bukorwa ukoresheje serivisi yawe; ubwishyu bwo muri Bank of Kigali bwemezwa n'ububiko. Ibyatumijwe ntibyemezwa kugeza ububiko bugenzuye ubwishyu.",
    "Product availability": "Ibicuruzwa bihari",
    "Stock is reserved when an order is placed. If an item is unavailable, contact support from your profile.": "Ibicuruzwa bibikwa igihe utumije. Niba igicuruzwa kitabonetse, vugana n'ubufasha muri profayili yawe.",
    "Questions or concerns": "Ibibazo cyangwa impungenge",
    "Sign in and submit a message or report from your profile. Replies are kept in your account inbox.": "Injira wohereze ubutumwa cyangwa raporo muri profayili yawe. Ibisubizo bizabikwa mu butumwa bwa konti yawe.",
    "We use account and order information to operate the store and provide customer support.": "Dukoresha amakuru ya konti n'ibyo watumije kugira ngo dukore ububiko kandi dutange ubufasha.",
    "Account and order details": "Amakuru ya konti n'ibitumizwa",
    "Your name, email, delivery address, payment method, payer phone or bank account number, cart, and order details are used to manage your account and fulfil your orders. Payer account details are visible only to you and authorised administrators handling that order.": "Amazina, imeyili, aderesi, uburyo bwo kwishyura, nomero ya telefoni cyangwa konti ya banki, agaseke n'amakuru y'ibitumizwa bikoreshwa mu gucunga konti no kuguha ibyo watumije. Amakuru ya konti ahabwa wowe n'abayobozi babifitiye uburenganzira gusa.",
    "Support conversations": "Ubutumwa bwo kugufasha",
    "Messages, wishes, issue reports, and replies are associated with your signed-in account so you and authorised store administrators can view the conversation.": "Ubutumwa, ibyifuzo, raporo n'ibisubizo bihuzwa na konti yawe kugira ngo wowe n'abayobozi babifitiye uburenganzira mubibone.",
    "Browser push notifications are optional. If enabled, the browser’s subscription is stored with your account so the store can send order and support updates. You can disable notifications in your profile or browser settings.": "Ubutumwa bwa browser si itegeko. Nubufungura, amakuru yabwo abikwa kuri konti yawe kugira ngo ububiko bukumenyeshe impinduka. Ushobora kubuzimya muri profayili cyangwa igenamiterere rya browser.",
    "Payment safety": "Umutekano w'ubwishyu",
    "The site does not request or store your mobile-money or banking PIN. Payer phone and account numbers are stored with the order and shared only with the customer and authorised administrators handling it.": "Uru rubuga ntirusaba cyangwa ngo rubike PIN ya banki cyangwa iya telefoni. Nomero ya telefoni cyangwa konti yo kwishyura ibikwa ku gitumijwe kandi ihabwa umukiriya n'abayobozi babifitiye uburenganzira gusa.",
    "For a privacy question, contact info@greenmarket.rw or write to ishconnlab@gmail.com.": "Ku kibazo cy'ibanga, andikira info@greenmarket.rw cyangwa ishconnlab@gmail.com.",
    "Explore the collection": "Reba ibicuruzwa",
    "Your favorites": "Ibyo ukunda",
    "WELCOME BACK": "Urahawe ikaze",
    "JOIN THE GOOD THINGS": "Tangira urugendo rwiza",
    "Could not load products.": "Ntibishobotse gupakira ibicuruzwa.",
    "Could not load your cart.": "Ntibishobotse gupakira agaseke kawe.",
    "Could not sign in. Please try again.": "Ntibishobotse kwinjira. Ongera ugerageze.",
    "Could not place your order.": "Ntibishobotse kohereza ubusabe bwawe.",
    "Sign in to add items to your cart.": "Injira kugira ngo ushyire ibicuruzwa mu gaseke.",
    "Your session expired. Please sign in again.": "Igihe cyawe cyo gukoresha cyarangiye. Ongera winjire.",
    "{name} added to your cart.": "{name} yashyizwe mu gaseke kawe.",
    "Welcome{suffix}!": "Urahawe ikaze{suffix}!",
    "YOUR PICKS": "Ibyo wahisemo",
    "Cart": "Agaseke",
    "Payment method": "Uburyo bwo kwishyura",
    "Product added.": "Igicuruzwa cyongeweho.",
    "Product updated.": "Igicuruzwa cyahinduwe.",
    "Product removed.": "Igicuruzwa cyakuweho.",
    "Could not save this product.": "Ntibishobotse kubika iki gicuruzwa.",
    "Could not remove this product.": "Ntibishobotse gukuraho iki gicuruzwa.",
    "Could not update this order.": "Ntibishobotse guhindura iki gitumizwa.",
    "Could not update payment status.": "Ntibishobotse guhindura imiterere y'ubwishyu.",
    "Could not send this reply.": "Ntibishobotse kohereza iki gisubizo.",
    "Remove “{name}” from the store?": "Ukureho “{name}” mu bubiko?",
    "Cancel this order? Its reserved stock will be returned.": "Uhagarike iki gitumizwa? Ibicuruzwa byari byabitswe birasubizwa.",
    "Order {code} updated.": "Icyatumijwe {code} cyahinduwe.",
    "Payment for order {code} updated.": "Ubwishyu bw'icyatumijwe {code} bwahinduwe.",
    "Exported a report for {count} orders.": "Raporo y'ibitumizwa {count} yakuweho.",
    "Could not create the order report PDF. Please try again.": "Ntibishobotse gukora raporo ya PDF. Ongera ugerageze.",
    "Reply sent to {name}.": "Igisubizo cyoherejwe kuri {name}.",
    "{count} new order or customer message{plural} received.": "Habonetse ibitumizwa cyangwa ubutumwa bushya {count}.",
    "Mark viewed": "Shyira ku byasomwe",
    "Fruit, Food, Devices...": "Imbuto, ibiribwa, ibikoresho...",
    "in stock": "birahari",
    "CUSTOMER CARE": "UBUFASHA KU BAKIRIYA",
    "Last reply": "Igisubizo giheruka",
    "The PDF includes customer, item, fulfilment, payment, and date details. Its QR code links back to the admin dashboard.": "PDF irimo amakuru y'umukiriya, ibicuruzwa, itangwa, ubwishyu n'amatariki. QR code iguhuza n'imbonerahamwe y'ubuyobozi.",
    "Could not load store management.": "Ntibishobotse gupakira imicungire y'ububiko.",
    "Could not check for new orders.": "Ntibishobotse kugenzura ibitumizwa bishya.",
    "Could not check for new customer messages.": "Ntibishobotse kugenzura ubutumwa bushya bw'abakiriya.",
    "No products match “{query}”. Try another search.": "Nta bicuruzwa bihuye na “{query}”. Gerageza gushakisha ukundi.",
    "Customer account unavailable": "Konti y'umukiriya ntiyabonetse",
    "Notifications": "Ubutumwa bukumenyesha",
    "Could not check notification settings.": "Ntibishobotse kugenzura igenamiterere ry'ubutumwa.",
    "Could not update notification settings.": "Ntibishobotse guhindura igenamiterere ry'ubutumwa.",
    "Order notifications are not configured yet": "Ubutumwa ku byo watumije ntiburategurwa.",
    "Allow notifications to receive order updates on this device.": "Emera ubutumwa kugira ngo wakire amakuru y'ibitumizwa kuri iki gikoresho.",
    "Notifications are blocked in browser settings. Allow them for this site, then try again.": "Ubutumwa bwabujijwe muri browser. Bwemere kuri uru rubuga, wongere ugerageze.",
    "This browser does not support order notifications.": "Iyi browser ntishyigikira ubutumwa ku byo watumije.",
    "Could not enable browser notifications.": "Ntibishobotse gufungura ubutumwa muri browser.",
    "Fresh market produce": "Imbuto nshya zo ku isoko",
    "Good things for your home": "Ibikoresho byiza byo mu rugo",
    "Everyday essentials": "Iby'ingenzi bya buri munsi",
    "Green Market, good finds daily": "Green Market, ibicuruzwa byiza buri munsi",
    "MARKET WATCH": "AMAKURU KU ISOKO",
    "NOW": "NONAHA",
    "Green Market promotions": "Kwamamaza kwa Green Market",
    "TRENDING AT THE MARKET": "IBIRI GUKUNDWA KU ISOKO",
    "Fresh picks for your week": "Ibyatoranyijwe bishya by'iki cyumweru",
    "See what just arrived": "Reba ibicuruzwa bimaze kugera",
    "GOOD THINGS, GROWING": "IBYIZA BIRIMO KONGERA",
    "Make everyday meals brighter": "Ryoherwa n'amafunguro ya buri munsi",
    "Browse market favourites": "Reba ibikunzwe ku isoko",
    "A LITTLE HOME REFRESH": "ONGERA UBWIZA MU RUGO",
    "Thoughtful finds for home": "Ibyatoranyijwe neza byo mu rugo",
    "Watch video": "Reba videwo",
    "Manage promotions": "Cunga amatangazo",
    "Edit promotion": "Hindura itangazo",
    "Create, update, publish, or remove offers and trending video stories shown under the navigation.": "Ongeraho, hindura, tangaza cyangwa ukureho amatangazo n'amakuru ya videwo agaragara munsi y'urubuga.",
    "promotions": "amatangazo",
    "Headline label": "Umutwe mugufi",
    "Promotion title": "Umutwe w'itangazo",
    "Short description": "Ibisobanuro bigufi",
    "Image or video thumbnail URL": "Aderesi y'ifoto cyangwa igaragara kuri videwo",
    "YouTube or Instagram video link (optional)": "Aderesi ya videwo ya YouTube cyangwa Instagram (si ngombwa)",
    "Video promotions open in a new tab. YouTube thumbnails are generated automatically; add an image URL for Instagram videos.": "Amatangazo ya videwo afunguka mu rundi rupapuro. Ifoto ya YouTube iboneka ako kanya; kuri Instagram shyiraho aderesi y'ifoto.",
    "Publish promotion": "Tangaza itangazo",
    "No promotions yet. Add one above.": "Nta matangazo arahari. Ongera rimwe hejuru.",
    "Video": "Videwo",
    "Published": "Ryatangajwe",
    "Hidden": "Rihishe",
    "Hide": "Hisha",
    "Publish": "Tangaza",
    "Promotion added.": "Itangazo ryongeweho.",
    "Promotion updated.": "Itangazo ryahinduwe.",
    "Promotion published.": "Itangazo ryatangajwe.",
    "Promotion hidden.": "Itangazo ryahishwe.",
    "Promotion removed.": "Itangazo ryakuweho.",
    "Remove this promotion from the ticker?": "Ukureho iri tangazo ku rutonde rugaragara?",
    "Could not save this promotion.": "Ntibishobotse kubika iri tangazo.",
    "Could not update this promotion.": "Ntibishobotse guhindura iri tangazo.",
    "Could not remove this promotion.": "Ntibishobotse gukuraho iri tangazo.",
    "Promotions could not be loaded.": "Ntibishobotse gupakira amatangazo.",
    "Product details coming soon.": "Ibisobanuro birambuye bizashyirwaho vuba.",
    "View product details": "Reba ibisobanuro birambuye by'igicuruzwa",
    "Availability": "Kuboneka",
    "Add useful product-specific details such as size, quantity, materials, ingredients, or how to use it. Customers can read the full description on the product card.": "Ongeraho amakuru y'igicuruzwa nk'ingano, umubare, ibikoresho cyakozwemo, ibikirimo cyangwa uko gikoreshwa. Abakiriya bashobora gusoma ibisobanuro byose ku ikarita y'igicuruzwa.",
    "Share this product": "Sangiza abandi iki gicuruzwa",
    "Product link copied. Paste it into Instagram to share.": "Aderesi y'igicuruzwa yakoporowe. Yishyire kuri Instagram kugira ngo usangize abandi.",
    "Copy the product link to share it on Instagram.": "Koporora aderesi y'igicuruzwa uyisangize abandi kuri Instagram.",
    "Install app": "Shyira porogaramu muri telefoni",
    "Green Market is installed.": "Green Market yashyizwe muri telefoni.",
    "Could not start installation. Use your browser menu to install the app.": "Ntibishobotse gutangiza ishyirwaho. Koresha menu ya browser ushyiremo porogaramu.",
    "404 illustration": "Ishusho igaragaza urupapuro rutabonetse",
    "Page not found": "Urupapuro ntirubonetse",
    "This page may have moved, or the address may be incorrect.": "Urupapuro rushobora kuba rwarimuwe cyangwa aderesi wanditse ikaba itari yo.",
    "Sell with us": "Dukorane mu bucuruzi",
    "Review note for seller": "Icyitonderwa cy'isuzuma kigenewe umucuruzi",
    "My store": "Ububiko bwanjye",
    "Loading store...": "Turimo gupakira ububiko...",
    "Store not found": "Ububiko ntibwabonetse",
    "Independent Green Market store": "Ububiko bwigenga bwa Green Market",
    "SHOP THIS STORE": "GURA MURI UBU BUBIKO",
    "Products from {store}": "Ibicuruzwa byo muri {store}",
    "Visit Green Market": "Sura Green Market",
    "This store has not added products yet.": "Ubu bubiko ntiburashyiraho ibicuruzwa.",
    "Loading seller dashboard...": "Turimo gupakira imbonerahamwe y'umucuruzi...",
    "SELL WITH GREEN MARKET": "CURUZA NA GREEN MARKET",
    "Open your own store": "Fungura ububiko bwawe",
    "Sign in to submit a store request. Green Market reviews every application before the store goes live.": "Injira wohereze ubusabe bwo gufungura ububiko. Green Market ibanza gusuzuma ubusabe mbere y'uko ububiko butangira gukora.",
    "SELLER WORKSPACE": "AHO UMUCURUZI AKORERA",
    "Your standalone store": "Ububiko bwawe bwigenga",
    "Manage your independent Green Market shop, products, and customer orders.": "Cunga ububiko bwawe bwigenga bwa Green Market, ibicuruzwa n'ibyo abakiriya batumije.",
    "Not applied": "Nta busabe watanze",
    "Store profile and settings": "Umwirondoro n'igenamiterere by'ububiko",
    "Apply to open a store": "Saba gufungura ububiko",
    "Open my store": "Fungura ububiko bwanjye",
    "Green Market review": "Isuzuma rya Green Market",
    "Your request is waiting for Green Market approval.": "Ubusabe bwawe butegereje kwemezwa na Green Market.",
    "Your store is paused by Green Market. You can view orders and update store details, but products are hidden until it is approved again.": "Green Market yahagaritse ububiko bwawe by'agateganyo. Ushobora kureba ibyo watumijwe no guhindura amakuru, ariko ibicuruzwa bizongera kugaragara ububiko bwemejwe.",
    "Store name": "Izina ry'ububiko",
    "Store URL name": "Izina rigaragara muri aderesi",
    "Store category": "Icyiciro cy'ububiko",
    "Contact phone": "Telefoni yo kuvugana",
    "Store email": "Imeyili y'ububiko",
    "Store address": "Aderesi y'ububiko",
    "Store description": "Ibisobanuro by'ububiko",
    "Store logo image URL": "Aderesi y'ifoto ya logo y'ububiko",
    "Store banner image URL": "Aderesi y'ifoto nini y'ububiko",
    "Submit store request": "Ohereza ubusabe bwo gufungura ububiko",
    "Update and resubmit": "Hindura wongere wohereze",
    "Save store settings": "Bika igenamiterere ry'ububiko",
    "STORE CATALOG": "IBICURUZWA BY'UBUBIKO",
    "Edit product": "Hindura igicuruzwa",
    "Add size, quantity, ingredients, materials, or usage details.": "Ongeraho ingano, umubare, ibikigize, ibikoresho cyakozwemo cyangwa uko gikoreshwa.",
    "CUSTOMER ORDERS": "IBYO ABAKIRIYA BATUMIJE",
    "Orders for {store}": "Ibyatumijwe muri {store}",
    "No orders have been placed for your store yet.": "Nta kintu kiratumizwa muri ubu bubiko.",
    "Store request sent for review.": "Ubusabe bwo gufungura ububiko bwoherejwe ngo busuzumwe.",
    "Store details saved.": "Amakuru y'ububiko yabitswe.",
    "MARKETPLACE": "ISOKO RIHURIWEHO",
    "Standalone store requests": "Ubusabe bw'ububiko bwigenga",
    "awaiting review": "butegereje gusuzumwa",
    "stores": "ububiko",
    "No standalone store requests yet.": "Nta busabe bw'ububiko bwigenga buraboneka.",
    "Independent store": "Ububiko bwigenga",
    "Store URL": "Aderesi y'ububiko",
    "Review note": "Icyitonderwa cy'isuzuma",
    "Approve": "Emeza",
    "Pause": "Hagarika by'agateganyo",
    "Resume": "Ongera utangize",
    "Reject": "Anga",
    "Store approved.": "Ububiko bwemejwe.",
    "Store paused.": "Ububiko bwahagaritswe by'agateganyo.",
    "Store request rejected.": "Ubusabe bw'ububiko bwanze.",
    "Store removed.": "Ububiko bwakuweho.",
    "Remove {store} and its active products? Historical orders will be kept.": "Ukureho {store} n'ibicuruzwa bikigaragara? Ibyatumijwe kera bizagumaho.",
    "Your store URL is already in use.": "Aderesi y'ububiko isanzwe irakoreshwa.",
    "Confirm your payment account": "Konti wakoresheje mu kwishyura",
    "Your payer account number is shared only with the store handling your order. Never share your banking PIN.": "Nomero ya konti wakoresheje ihabwa gusa ububiko burimo kugutegurira ibyo watumije. Ntugasangize abandi PIN ya banki yawe.",
    "Green Market": "Green Market",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try {
      return localStorage.getItem("green-market-language") === "rw" ? "rw" : "en";
    } catch {
      return "en";
    }
  });

  useEffect(() => {
    document.documentElement.lang = language;
    try {
      localStorage.setItem("green-market-language", language);
    } catch {
      // Language still applies for the current session when storage is unavailable.
    }
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (text, replacements = {}) => {
      const translated = language === "rw" ? translations.rw[text] || text : text;
      return Object.entries(replacements).reduce(
        (result, [key, replacement]) => result.replaceAll(`{${key}}`, String(replacement)),
        translated
      );
    },
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}
